### ISSUE TITLE
AttributeError: TCliqueOverlap_GetCPMCommunities

### ISSUE THREAD

**Issue by satyaborg** [snap-stanford/MetroMaps#2]
Hi,

First off, thanks for this brilliant package. The concept of MetroMaps is really cool!

We wanted to explore this for visualizing narratives around cycles of disadvantage in media which might potentially feature as part of an art installation later this year.

I've setup all the pre-requisites as per the instructions, however when running the LOTR example `python2.7 mmrun.py lotr.yaml` I get the following error:

```
Traceback (most recent call last):
  File "mmrun.py", line 106, in <module>
    main(config_file, defaults)
  File "mmrun.py", line 94, in main
    Run(config_dict)
  File "mmrun.py", line 64, in Run
    Run_clustering_handler(configs)
  File "mmrun.py", line 40, in Run_clustering_handler
    clustering_handler.run()
  File "/home/ubuntu/MetroMaps/mm/mapgen/cluster_generator.py", line 205, in run
    communities = self.clique_percolation(g, k, id_to_token)
  File "/home/ubuntu/MetroMaps/mm/mapgen/cluster_generator.py", line 172, in clique_percolation
    snap.TCliqueOverlap_GetCPMCommunities(g, k, Communities)
AttributeError: 'module' object has no attribute 'TCliqueOverlap_GetCPMCommunities'
```

As I understand, the latest version for `snappy` should include `TCliqueOverlap_GetCPMCommunities` since it is [present](https://snap.stanford.edu/snap/doc/snapdev-ref/dd/d2f/classTCliqueOverlap.html#a4f4c1df8446c41f62a3b59be4c4c91a4) in snap==6.0 

Here's the output from `pip list` in my virtual environment:

```
Package         Version
--------------- -------
Jinja2          2.7.2
MarkupSafe      0.21
networkx        1.8.1
nose            1.3.0
numpy           1.8.0
pip             20.3.4
pkg-resources   0.0.0
pyparsing       2.0.1
python-dateutil 2.2
PyYAML          3.10
setuptools      44.1.1
six             1.16.0
snap-stanford   6.0.0
wheel           0.36.2
```

Really appreciate it, thanks!

**Comment by roks** [comment]
Thank you very much for your feedback! You are correct, this is an issue in snap.py. I filed a report there. We will try to fix it with the next release. In the meantime, you can try an older release of snap.py: http://snap.stanford.edu/snappy-1.1/. There is a small chance that it might work. If not, the new release will be required.

**Comment by satyaborg** [comment]
@roks thank you for the suggestion re `snappy-1.1` .. it finally worked! (w/ centOS 7, Python2.7)
Hopefully, this also helps others if they were struggling with a similar issue :) 
Cheers!

**Comment by bystran** [comment]
Just thought someone might find this useful. 

I installed `snappy-1.1` like satyaborg but it still wouldn't run - for some reason the package didn't contain any reference to the method `snap.TCliqueOverlap_GetCPMCommunities(*args)`. 

I dug in the source code and found that you can call the method by calling `snap.TCliqueOverlap.GetCPMCommunities(*args)` instead of  `snap.TCliqueOverlap_GetCPMCommunities(*args)`. 

_windows 11 python2.7_
